FROM golang:1.24-alpine AS builder
WORKDIR /app
COPY . .
RUN go build -o portal-app ./cmd/portal 

FROM alpine:latest
WORKDIR /root/
COPY --from=builder /app/portal-app .
COPY --from=builder /app/internal/portal/templates ./internal/portal/templates
CMD ["./portal-app"]